import "./globals.css";
import { ReduxProvider } from "@/store/ReduxProvider";
import { store } from "@/store/store";

export const metadata = {
  title: "Next Store App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider store={store}>{children}</ReduxProvider>
      </body>
    </html>
  );
}
